### PR TITLE
Upgraded to vaadin-8 and removed dependency to testbench

### PR DESCRIPTION
**Pull request by octavm**
Upgraded to vaadin-8 and removed dependency to testbench so everyone can run tests.
Maybe it can be pulled into a new 'vaadin-8' branch rather than the 'master'

### CODE REVIEW

**Comment by octavm** [comment]
Yes, I'll accept the challenge :-) I'd like to take ownership. Thanks.

**Comment by mstahv** [comment]
Awesome, I'll look with my colleague so that the directory addon becomes yours. I'll move the ownership of this repo to you so that all the issues etc remain.

I'm of course in the future still available for reviews and comments as well!

**Comment by mstahv** [comment]
Awesome! And of course I'm still here to help you if you need an extra pair of eyes for something.

My colleague will change the ownership of the add-ons in the directory service soon. We could also move this repo to you, so then the full history with issues remains. For that you'd need to rename your fork to something else. Can you do that and let me know?

**Comment by octavm** [comment]
Great! Thanks for trusting me with this add-on.
I can remove my fork completely since right now its even with master. I suppose I won't need it anyway since I'll be able to commit changes directly to this branch.

**Comment by octavm** [comment]
Done! I have deleted my fork.

**Comment by mstahv** [comment]
Transferring initiated, you probably have some notification from GitHub. In the Directory the add-on is now tied to your account.

**Pull request merged**
